image:
  repository: prom/pushgateway
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9091
  targetPort: 9091

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - atlasrucioint-2csnpmpztgy3-minion-2.cern.ch

serviceMonitor:
  enabled: True
  namespace: monitoring

  additionalLabels:
    release: prometheus-operator

  honorLabels: true
