{
 "title": "Rucio Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "[Conveyor] Queues",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(conveyor_queues_requests{state='waiting'})",
     "legendFormat": "Waiting Requests in Rucio"
    },
    {
     "expr": "sum(conveyor_queues_requests{state='done'})",
     "legendFormat": "Unacknoledged Transfers"
    },
    {
     "expr": "sum(conveyor_queues_requests{state='queued',external_host='no_fts_host'})",
     "legendFormat": "Queued Requests in Rucio"
    },
    {
     "expr": "sum(conveyor_queues_requests{state='submitted',external_host!='no_fts_host'})",
     "legendFormat": "Queued Requests in FTS"
    },
    { "expr": "sum(fts_submitted)", "legendFormat": "Submitted Requests by Conveyor" }
   ]
  },
  {
   "title": "[Conveyor] Submitted Requests by Activity",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(conveyor_queues_requests{external_host!='null_fts_host',state='submitted'}) by (activity)",
     "legendFormat": "{{activity}}"
    }
   ]
  },
  {
   "title": "[Conveyor] Queued Requests by Activity",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(conveyor_queues_requests{state='queued'}) by (activity)",
     "legendFormat": "{{activity}}"
    }
   ]
  },
  {
   "title": "[Conveyor] Submitted Requests by FTS",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fts_submitted) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "[Hermes] Messages Queue Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hermes_queues_messages", "legendFormat": "Messages" }
   ]
  },
  {
   "title": "[Judge] Stuck Rules",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "judge_stuck_rules_with_missing_source_replica",
     "legendFormat": "With Missing Source Replica"
    },
    {
     "expr": "judge_stuck_rules_without_missing_source_replica",
     "legendFormat": "Without Missing Source Replica"
    }
   ]
  },
  {
   "title": "[Judge] Waiting Rules",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "judge_waiting_dids", "legendFormat": "Unevaluated DIDs" }
   ]
  },
  {
   "title": "[Judge] Injecting Rules",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "judge_injecting_rules", "legendFormat": "Injecting Rules" }
   ]
  },
  {
   "title": "[Judge] Expired Rules",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "judge_expired_rules", "legendFormat": "Expired Rules" }
   ]
  },
  {
   "title": "[Judge] Lifetimed Rules",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "judge_lifetimed_rules", "legendFormat": "Lifetimed Rules" }
   ]
  },
  {
   "title": "[Undertaker] Expired DIDs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "undertaker_expired_dids", "legendFormat": "Expired DIDs" }
   ]
  },
  {
   "title": "[Transmogrifier] New DIDs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "transmogrifier_new_dids", "legendFormat": "New DIDs" }
   ]
  },
  {
   "title": "[Reaper] Unlocked Replicas",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "reaper_expired_replicas", "legendFormat": "Expired Replicas" },
    { "expr": "reaper_unlocked_replicas", "legendFormat": "Unlocked Replicas" }
   ]
  }
 ]
}